name: mcp_example
description: Example for the flutter_mcp package
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter_mcp:
    path: ../
  logging: ^1.2.0
  web_socket_channel: ^2.4.0
